server:
  port: 5555

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service
    api-b:
      path: /api-b/**
      serviceId: feign-consumer